export const ROUTES = {
  ROOT: {
    PATH: '/api',
  },
  AUTH: {
    PATH: '/auth',
    LOGIN: '/login',
    LOGOUT: '/logout',
    REGISTER: '/register',
  },
  MEALPLAN: {
    PATH: '/planner',
    ADD: '/',
    GET: '/',
    GET_LATEST: '/copy',
    GET_GROCERIES: '/groceries',
    EDIT: '/:id',
    DELETE: '/:id',
  },
  USER: {
    PATH: '/user',
    CHANGE_PASSWORD: '/change-password',
    NUTRITION_TARGET: '/nutrition-target',
    GET_STATS: '/stats',
    EDIT_STATS: '/stats',
    GET_NUTRI_BY_STATS: '/nutrition-by-stats',
    GET_PRIMARY_DIET: '/primary-diet',
    EDIT_PRIMARY_DIET: '/primary-diet',
    GET_FOOD_EXCLUSIONS: '/food-exclusions',
    EDIT_FOOD_EXCLUSIONS: '/food-exclusions',
    GET_ME: '/me',
  },
  COLLECTION: {
    PATH: '/collections',
    GET: '/',
    GET_BY_ID: '/:id',
    POST: '/',
    PUT: '/:id',
    DELETE: '/:id',
  },
  FOOD: {
    PATH: '/foods',
    GETLIST: '/',
    GET_BY_ID: '/:id',
    SEARCH: '/search',
  },
  API_DOCS: '/api-docs',
};
