export const ROUTES = {
  ROOT: {
    PATH: '/api',
  },
  AUTH: {
    PATH: '/auth',
    LOGIN: '/login',
    LOGOUT: '/logout',
    REGISTER: '/register',
  },
  AI: {
    PATH: '/ai',
    CHAT: '/chat',
  },
  MEALPLAN: {
    PATH: '/planner',
    ADD: '/',
    GET: '/',
    GET_LATEST: '/copy',
    GET_GROCERIES: '/groceries',
    EDIT: '/:id',
    DELETE: '/:id',
    AUTO_GENERATE: '/auto-generate',
    AUTO_GENERATE_WEEK: '/auto-generate-week',
    SWAP_OPTIONS: '/:id/swap-options',
    SWAP: '/:id/swap',
    ADMIN_LIST: '/admin',
    ADMIN_CREATE: '/admin',
    ADMIN_UPDATE: '/admin/:id',
    ADMIN_DELETE: '/admin/:id',
  },
  USER: {
    PATH: '/user',
    CHANGE_PASSWORD: '/change-password',
    NUTRITION_TARGET: '/nutrition-target',
    GET_STATS: '/stats',
    EDIT_STATS: '/stats',
    GET_NUTRI_BY_STATS: '/nutrition-by-stats',
    GET_PRIMARY_DIET: '/primary-diet',
    EDIT_PRIMARY_DIET: '/primary-diet',
    GET_FOOD_EXCLUSIONS: '/food-exclusions',
    EDIT_FOOD_EXCLUSIONS: '/food-exclusions',
    GET_ME: '/me',
    EDIT_AVATAR: '/avatar',
    ADMIN_LIST: '/admin',
    ADMIN_GET_BY_ID: '/admin/:id',
    ADMIN_UPDATE: '/admin/:id',
    ADMIN_DELETE: '/admin/:id',
  },
  COLLECTION: {
    PATH: '/collections',
    GET: '/',
    CURATED: '/curated',
    GET_BY_ID: '/:id',
    POST: '/',
    PUT: '/:id',
    DELETE: '/:id',
    GET_FAVORITES: '/favorites',
    UPDATE_FAVORITES: '/favorites',
    GET_EXCLUSIONS: '/exclusions',
    UPDATE_EXCLUSIONS: '/exclusions',
    ADMIN_LIST: '/admin',
    ADMIN_GET_BY_ID: '/admin/:id',
    ADMIN_CREATE: '/admin',
    ADMIN_UPDATE: '/admin/:id',
    ADMIN_DELETE: '/admin/:id',
  },
  CATEGORY: {
    PATH: '/categories',
    GET: '/',
    ADMIN_LIST: '/admin',
    ADMIN_CREATE: '/admin',
    ADMIN_UPDATE: '/admin/:id',
    ADMIN_DELETE: '/admin/:id',
  },
  FOOD: {
    PATH: '/foods',
    GETLIST: '/',
    GET_BY_ID: '/:id',
    SEARCH: '/search',
    CREATE: '/',
    UPDATE: '/:id',
    DELETE: '/:id',
  },
  ARTICLES: {
    PATH: '/articles',
    GET: '/',
    ADMIN_LIST: '/admin',
    ADMIN_GET_BY_ID: '/admin/:id',
    GET_BY_SLUG: '/:slug',
    CREATE: '/',
    UPDATE: '/:id',
    DELETE: '/:id',
  },
  ANALYTICS: {
    PATH: '/analytics',
    FOOD_VIEW: '/food-view',
    ARTICLE_VIEW: '/article-view',
    CURATED_COLLECTION_VIEW: '/curated-collection-view',
    CURATED_COLLECTION_COPY: '/curated-collection-copy',
    ADMIN_DASHBOARD: '/admin/dashboard',
  },
  PANTRY: {
    PATH: '/pantry',
    GET: '/',
    POST: '/',
    PUT: '/:id',
    DELETE: '/:id',
    CONSUME: '/consume',
    SUGGESTIONS: '/suggestions',
  },
  API_DOCS: '/api-docs',
};
