import { model, PaginateModel, Schema } from 'mongoose';
import MongooseDelete, { SoftDeleteModel } from 'mongoose-delete';
import paginate from 'mongoose-paginate-v2';

import type { Food } from '@/types';

export const NutritionSchema = new Schema({
  carbs: Number,
  fat: Number,
  proteins: Number,
  calories: Number,
  netCarbs: Number,
  caffeine: Number,
  theobromine: Number,
  fiber: Number,
  calcium: Number,
  iron: Number,
  magnesium: Number,
  phosphorus: Number,
  potassium: Number,
  sodium: Number,
  zinc: Number,
  copper: Number,
  fluoride: Number,
  manganese: Number,
  selenium: Number,
  vitAIu: Number,
  vitA: Number,
  vitB6: Number,
  vitB12: Number,
  vitC: Number,
  vitDIu: Number,
  vitD: Number,
  vitD2: Number,
  vitD3: Number,
  vitE: Number,
  vitK: Number,
  retinol: Number,
  lycopene: Number,
  thiamine: Number,
  riboflavin: Number,
  niacin: Number,
  folate: Number,
  choline: Number,
  betaCarotene: Number,
  alphaCarotene: Number,
  cholesterol: Number,
  betaine: Number,
  sugar: Number,
  sucrose: Number,
  glucose: Number,
  fructose: Number,
  lactose: Number,
  maltose: Number,
  galactose: Number,
  starch: Number,
  alcohol: Number,
  water: Number,
  tryptophan: Number,
  threonine: Number,
  isoleucine: Number,
  leucine: Number,
  lysine: Number,
  methionine: Number,
  cystine: Number,
  phenylalanine: Number,
  tyrosine: Number,
  valine: Number,
  arginine: Number,
  histidine: Number,
  alanine: Number,
  asparticAcid: Number,
  glycine: Number,
  proline: Number,
  serine: Number,
  hydroxyproline: Number,
  transFats: Number,
  saturatedFats: Number,
  monounsaturatedFats: Number,
  polyunsaturatedFats: Number,
  alaFattyAcid: Number,
  dhaFattyAcid: Number,
  epaFattyAcid: Number,
  dpaFattyAcid: Number,
  totalOmega3: Number,
  totalOmega6: Number,
});

export const PropertySchema = new Schema({
  veggieServings: Number,
  fruitServings: Number,
  numberOfIngredients: Number,
  singleServing: Boolean,
  canBeBulk: Boolean,
  keepsWell: Boolean,
  allowPublic: Boolean,
  needsBlender: Boolean,
  needsOven: Boolean,
  needsStove: Boolean,
  needsSlowCooker: Boolean,
  needsToaster: Boolean,
  needsFoodProcessor: Boolean,
  needsMicrowave: Boolean,
  needsGrill: Boolean,
  blatantlyUnhealthy: Boolean,
  prepDayBefore: Boolean,
  complexity: Number,
  mainDish: Boolean,
  sideDish: Boolean,
  perishable: Boolean,
  expirationTime: Number,
  isBasicFood: Boolean,
  prepTime: Number,
  waitTime: Number,
  totalTime: Number,
  isBreakfast: Boolean,
  isLunch: Boolean,
  isDinner: Boolean,
  isSnack: Boolean,
  isDessert: Boolean,
  majorIngredients: String,
});

const FoodSchema = new Schema<Food>(
  {
    name: { type: String, required: true },
    imgUrls: { type: [String], required: false },
    nutrition: NutritionSchema,
    property: PropertySchema,
    videoUrl: { type: String, required: false },
    defaultUnit: { type: Number, default: 0 },
    units: {
      type: [
        {
          amount: { type: Number, default: 1 },
          description: { type: String, default: 'serving' },
        },
      ],
      default: [{ amount: 1, description: 'serving' }],
    },
    directions: { type: [String], required: false },
    ingredients: {
      type: [
        {
          ingredientFoodId: {
            type: Schema.Types.ObjectId,
            ref: 'Food',
            required: true,
          },
          amount: { type: Number, required: true },
          unit: { type: Number, required: true },
          preparation: { type: String, required: false },
        },
      ],
      required: false,
    },
    description: { type: String, required: false },
    isRecipe: { type: Boolean, required: true },
    isCustom: { type: Boolean, required: true },
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: false },
    categories: [{ type: Number }],
  },
  { timestamps: true, autoCreate: true },
);

FoodSchema.plugin(MongooseDelete, { deletedAt: true, overrideMethods: true });
FoodSchema.plugin(paginate);

export const FoodModel = model<Food>(
  'Food',
  FoodSchema,
) as SoftDeleteModel<Food> & PaginateModel<Food>;
